---
title: "PML 05"
author: "Angga Fathan Rofiqy"
date: "`r Sys.Date()`"
output: html_document
---

# Latihan

```{r}
path <- function() gsub  ( "\\\\",  "/",  readClipboard ()  )
#Copy path, Panggil function di console
#Copy r path, paste ke var yang diinginkan
```

```{r setup, include=FALSE, echo=FALSE}
require("knitr")
opts_knit$set(root.dir = "C:/Users/Fathan/Documents/Obsidian Vault/2. Kuliah/Smt 5/3. Pengantar Model Linier")
```

```{r}
#                      -=( Install & Load Package Function )=-
install_load <- function (package1, ...)  {   

   # convert arguments to vector
   packages <- c(package1, ...)

   # start loop to determine if each package is installed
   for(package in packages){

       # if package is installed locally, load
       if(package %in% rownames(installed.packages()))
          do.call('library', list(package))

       # if package is not installed locally, download, then load
       else {
          install.packages(package)
          do.call("library", list(package))
       }
   } 
}
```

### Data

```{r}
data <- read.csv("scrap price.csv")
```

```{r}
#Peuba y
y  <- data$price
kable(head(y))
```

```{r}
#Peubah X
x0 <- rep(1,nrow(data))
x1 <- data$citympg
x2 <- data$highwaympg
x3 <- data$peakrpm
x4 <- data$horsepower
x5 <- data$enginesize

#Matriks X
X <- cbind(x0,x1,x2,x3,x4,x5)
kable(head(X))
```

### 4. Plot

```{r fig1, fig.height = 9, fig.width = 16, fig.align = "center"}
par(mfrow = c(2,3))
plot(y, x1); plot(y, x2); plot(y, x3); plot(y, x4); plot(y, x5)
```

x3 bukan linier. Jangan pake x3 (peak rpm)

```{r}
#Matriks X
X <- cbind(x0,x1,x2,x4,x5)
kable(head(X))
```

### 1. Koefisien regresi

```{r}
beta = solve(t(X) %*% X) %*% t(X) %*% y; beta
```

### $\hat{y}$

```{r}
yhat <- X %*% beta
kable(head(yhat))
```

### Sisaan

```{r}
res <- y-yhat
kable(head(res))
```

### n & p

```{r}
p <- qr(X)$rank; p
```

```{r}
n <- nrow(X); n
```

### 2. Ragam Galat

```{r}
yup = y - (X %*% beta)
ragam = (t(yup) %*% yup)/(n-p); ragam
```

Cari ragam dari beta

```{r}
install_load('MASS')
var.beta <- as.numeric(t(res) %*% res/(n - p)) * ginv(t(X) %*% X);  var.beta 
```

### 3. Interval kepercayaan

```{r}
alpha <- 10/100 #alpha 5%
t <-qt(1 - alpha/2, n - p) #nilai t tabel
conf.int <- round(cbind(beta - t*sqrt(diag(var.beta)), 
                        beta + t*sqrt(diag(var.beta))), 5)
conf.int
```

cek dengan package

```{r}
#fit model with standard R lm package
r.fit <- lm(y ~ x1 + x2 + x4 + x5)
#show confidence intervals in R
round(confint(r.fit, names(r.fit$coef), level = 0.90), n-p)
```

### Var important

```{r}
install_load('caret')
print(varImp(r.fit))
```

Terlihat bahwa var urutan var important adalah x5, x4, x2, x1

### Plot Var Important

```{r fig2, fig.height = 5, fig.width = 5, fig.align = "center"}
plot(y, x5)
```
